// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7tMkwZS2Cl7RdJqSNUsXbKpGv_6E-eG0',
    appId: '1:755916720907:web:0c75e8fe4790729f07f00e',
    messagingSenderId: '755916720907',
    projectId: 'roomantics-8eafd',
    authDomain: 'roomantics-8eafd.firebaseapp.com',
    databaseURL: 'https://roomantics-8eafd-default-rtdb.firebaseio.com',
    storageBucket: 'roomantics-8eafd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwp6vOxoKuLczllyxJD8Oizqv3P7XoBxI',
    appId: '1:755916720907:android:47bb829313b5fa3107f00e',
    messagingSenderId: '755916720907',
    projectId: 'roomantics-8eafd',
    databaseURL: 'https://roomantics-8eafd-default-rtdb.firebaseio.com',
    storageBucket: 'roomantics-8eafd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApY4Yu_3TBZuxwufaleloQ8ocMI-qdNdo',
    appId: '1:755916720907:ios:f6f268a81cea117b07f00e',
    messagingSenderId: '755916720907',
    projectId: 'roomantics-8eafd',
    databaseURL: 'https://roomantics-8eafd-default-rtdb.firebaseio.com',
    storageBucket: 'roomantics-8eafd.firebasestorage.app',
    iosBundleId: 'com.example.roomantic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApY4Yu_3TBZuxwufaleloQ8ocMI-qdNdo',
    appId: '1:755916720907:ios:f6f268a81cea117b07f00e',
    messagingSenderId: '755916720907',
    projectId: 'roomantics-8eafd',
    databaseURL: 'https://roomantics-8eafd-default-rtdb.firebaseio.com',
    storageBucket: 'roomantics-8eafd.firebasestorage.app',
    iosBundleId: 'com.example.roomantic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7tMkwZS2Cl7RdJqSNUsXbKpGv_6E-eG0',
    appId: '1:755916720907:web:e7b7c4877a4af2c407f00e',
    messagingSenderId: '755916720907',
    projectId: 'roomantics-8eafd',
    authDomain: 'roomantics-8eafd.firebaseapp.com',
    databaseURL: 'https://roomantics-8eafd-default-rtdb.firebaseio.com',
    storageBucket: 'roomantics-8eafd.firebasestorage.app',
  );
}
